### ISSUE TITLE
What is "conv2alg.txt" for ?

### ISSUE THREAD

**Issue by ikaroso** [mit-han-lab/inter-operator-scheduler#16]
Hi,
  I got an interesting problem, though solved, i am still curious about the usage of "conv2alg.txt".
  And I reproduce it with an example.
  ```pythoh
import ios
import numpy as np

graph=ios.models.nasnet_large()
graph.sequential_schedule()

seq = 0
for i in range(10):
    latency = ios.ios_runtime.graph_latency(graph, batch_size=1, repeat=6)
    print(f' Sequential schedule: {np.mean(latency):.3f} ms')

  ```
  The story is that I first run the above code, "test.py" on a PC with a GTX1060. Then, I copy the "test.py" and "conv2alg.txt" to another PC with a RTX3080. When I run the code on the latter PC, amazing things happen. The output inference latency is very high (around 40ms), which is obviously not correct. After trying everything, I remove "conv2alg.txt" and problem solved (the output latency changes to around 17ms which is the same as the latency I have saw before). 

  I checked the repo and it seems "conv2alg.txt" has something to do with ios runtime, but I am not sure. Would you please tell me what's happening here? THX!

**Comment by yaoyaoding** [comment]
Hi @ikaroso,

What you observed is expected. The 'conv2alg.txt' file contains the mapping from the [convolution key](https://github.com/mit-han-lab/inter-operator-scheduler/blob/91963c06051c58c7b92e8ec57a5a98788b5f4c01/src/ios/ios_runtime.cu#L59-L80) (nchw, kernel size, strides, padding) to the [algorithms](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnConvolutionFwdAlgo_t) used by cudnn. 

When we first run IOS, we will benchmark and choose the best algorithm for each convolution configuration, and store the mapping in the file. In subsequent runs, the file will be used instead of re-benchmarking for stability.

When you use one cache on another gpu, the algorithm might not be the best choice on that gpu, thus the performance would drop.

**Comment by ikaroso** [comment]
Hi @yaoyaoding ,
  Yeah, thx for your reply and it makes sense.  I still got a lot to learn.
  Thank you very much.
