### ISSUE TITLE
ios parameters

### ISSUE THREAD

**Issue by heart1998** [mit-han-lab/inter-operator-scheduler#8]
how to new IOS flops,kernels....

**Comment by heart1998** [comment]
how to know IOS memory,flops,kernels....

**Comment by yaoyaoding** [comment]
Hi,

You can use the `flops()`, `memory_access()` and `kernels()` member function of `ios.ir.Graph` object to get the memory flops, memory access, and memory access number. The following is code snippet is an example.

```python
import os
import numpy as np
import ios


def main():
    graph = ios.models.inception_v3()

    graph.sequential_schedule()
    latency = ios.ios_runtime.graph_latency(graph, batch_size=1, repeat=6)
    print('{:>30}: {}'.format('seq flops (flops)', graph.flops()))
    print('{:>30}: {}'.format('seq memory access (bytes)', graph.memory_access()))
    print('{:>30}: {}'.format('seq kernels', graph.kernels()))

    optimized_graph = ios.optimize(graph, batch_size=1)
    optimized_latency = ios.ios_runtime.graph_latency(optimized_graph, batch_size=1, repeat=6)
    print('{:>30}: {}'.format('ios flops (flops)', optimized_graph.flops()))
    print('{:>30}: {}'.format('ios memory access (bytes)', optimized_graph.memory_access()))
    print('{:>30}: {}'.format('ios kernels', optimized_graph.kernels()))

    os.makedirs("./outputs/", exist_ok=True)
    ios.draw(optimized_graph, fname=f'optimized_{graph.name}.png', label=f'Optimized Graph, Latency = {np.mean(optimized_latency):.3f}')
    print(f' Sequential schedule: {np.mean(latency):.3f} ms')
    print(f'  Optimized schedule: {np.mean(optimized_latency):.3f} ms')


if __name__ == '__main__':
    main()
```

FYI: If you want to benchmark IOS, I would suggest doing it on cuDNN 7.6.5. The kernels in the new version of cuDNN (i.e., 8.*.*) are not good at inter-op parallelization. It might because they do some pre-processing when launching a new kernel (e.g., [set the cache config](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXECUTION.html#group__CUDART__EXECUTION_1g6699ca1943ac2655effa0d571b2f4f15)) that would trigger the kernel serialization in the new version of cuDNN.
